--- #YAML:1.0
name:               Apache-Singleton
version:            0.11
abstract:           Singleton class for mod_perl
author:
    - Michael Schout <mschout@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Apache::Test:  1.26
    mod_perl2:     1.999022
    Test::More:    0.32
resources:
    bugtracker:  http://rt.cpan.org/NoAuth/Bugs.html?Dist=Apache-Singleton
    homepage:    http://github.com/mschout/apache-singleton/downloads
    repository:  http://github.com/mschout/apache-singleton
no_index:
    directory:
        - t
        - inc
        - t
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
